### ISSUE TITLE
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options.

### ISSUE THREAD

**Issue by sachinjm** [cauchyturing/UCR_Time_Series_Classification_Deep_Learning_Baseline#1]
While running ResNet.py on cpu, I am getting following error,

AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options.

Please help

**Comment by cauchyturing** [comment]
@sachinjm The code are fully tested on the tensorflow backend. I will take a look at the issue related to theano, and I suggest you switch to the tensorflow backend and try again (especially the CPU tf is quite easy to install).

**Comment by sachinjm** [comment]
its selecting theano by default
